version: 0.0
os: linux

files:
  - source: .
    destination: /home/ec2-user/khatabook_backend
    overwrite: yes

hooks:
  BeforeInstall:
    - location: scripts/cleanup.sh
      runas: ec2-user

  AfterInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ec2-user
