# Generated by Django 5.2.8 on 2025-11-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_created_at_user_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imges',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/'),
        ),
    ]
